### PR TITLE
SPOT-223 Unable to call 'authenticate' method in Kerberos (spot-ingest/common/kerberos.py)

### PR DESCRIPTION
**Pull request by bjigmp**
Fixed tabs to spaces in authenticate method so now it is related to Kerberos class

### CODE REVIEW

**Comment by natedogs911** [comment]
+1 from me
`"-kt"` is something that i think is an ok short term fix to make sure it's working as intended but i think the whole module needs some more thought.

**Comment by solrac901** [comment]
+1

**Comment by vgonzale78** [comment]
+1

**Comment by bjigmp** [comment]
It was already fixed in https://github.com/apache/incubator-spot/pull/134
Closed this PR

**Pull request closed without merging**
