### PR TITLE
SPOT-226. [Ingest] StreamSets pipeline configurations for ODM ingest

### PR DESCRIPTION
**Pull request by jnatkins**
This will add StreamSets pipeline configurations for Qualys APIs, Centrify Identity Platform events, and Windows Events. In an effort to provide some more visibility into the logic here, I'm attaching screenshots of the pipelines as they would be imported into the SDC. They're all parameterized, so that they can be started using filled-in variables relevant to the Spot environment.

screen shot 2017-09-21 at 11 12 17 am
screen shot 2017-09-21 at 11 12 36 am
screen shot 2017-09-21 at 11 12 49 am
screen shot 2017-09-21 at 11 13 05 am
screen shot 2017-09-21 at 11 13 41 am

### CODE REVIEW

**Comment by mhicks-cloudera-com** [comment]
+1

**Comment by jarcec** [comment]
+1

**Comment by solrac901** [comment]
+1

**Comment by natedogs911** [comment]
+1

**Comment by natedogs911** [comment]
As an added comment i think some work should be done to see if this is relevant to PR #69

**Comment by castleguarders** [comment]
Is there follow on code landing to be able to use these configurations? At least the 'free' ones like windows events? Otherwise, why have these configs here?

**Comment by jarcec** [comment]
The JSON files are can be used by another open source project called [Data Collector](https://github.com/streamsets/datacollector) @castleguarders . The general idea behind this PR is described in the [umbrella JIRA SPOT-232](https://issues.apache.org/jira/browse/SPOT-232) - to provide almost plug&play configuration that anyone can deploy to get started :)

**Comment by natedogs911** [comment]
Merging...

**Comment by natedogs911** [comment]
@castleguarders I think we need to review the offerings and adapt the current setup scripts + documentation to properly land these. that is probably an ongoing effort.

**Pull request merged**
