### PR TITLE
Spot-35 Adding Apache license to hql files and removing references to spot 0.9 in spot setup

### PR DESCRIPTION
**Pull request by moy8011**
- Adding Apache license to hql files
- Adding Apache license to spot.conf file 
- Removing references to spot 0.9 in spot setup
- Adjusting impala-shell command execution to bypass sql exceptions in hdfs_setup.sh

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by LedaLima** [comment]
+1

**Comment by lujacab** [comment]
+1

**Comment by natedogs911** [comment]
+1

**Comment by lujacab** [comment]
@moy8011, need to edit and replace the references to ## Migrating OA Data from Spot 0.9 to 1.0
on spot-setup/README.md and  spot-setup/migration/README.md

**Pull request closed without merging**
