### PR TITLE
add Apache Foundation links on supporting apache page

### PR DESCRIPTION
**Pull request by yellingviv**

### CODE REVIEW

**Comment by TaddWood** [comment]
+1, @yellingviv a few tweaks:

- Let's make the title - Apache Software Foundation Resources
- Change "Thanks" to "Thanks to the ASF’s sponsors" and just put the link on the "Thanks" text.
- Can we also make all the URLs use HTTPS for consistency?

**Comment by yellingviv** [comment]
I will get on this tomorrow!

**Comment by yellingviv** [comment]
Derp derp derp :)

**Comment by jfn6030217** [comment]
+1

**Comment by TaddWood** [comment]
@yellingviv can you also add the Apache Security link to this list?  Otherwise its ready to merge in :)

**Pull request merged**
