### PR TITLE
Spot 35 graphql api

### PR DESCRIPTION
**Pull request by EverLoSa**
Apache incubator-spot:  Release 1.0
[Release Notes](https://issues.apache.org/jira/browse/SPOT-154)

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by vgonzale78** [comment]
+1

**Comment by lujacab** [comment]
+1

**Comment by moy8011** [comment]
+1

**Comment by natedogs911** [comment]
I think this should be squashed when merged

**Comment by natedogs911** [comment]
+1

**Comment by LedaLima** [comment]
+1

**Pull request merged**
