### PR TITLE
OA Bug fix at DNS and Proxy to skip reputation check

### PR DESCRIPTION
**Pull request by LedaLima**
In order to skip reputation check for dns and/or proxy, the user can leave the reputation.config file empty
Reported in Jira
https://issues.apache.org/jira/browse/SPOT-31

### CODE REVIEW

**Comment by EverLoSa** [comment]
+1

**Comment by rabarona** [comment]
+1

**Comment by lujacab** [comment]
Done, Pass the Test OA Dns and Proxy, Ready to merge.

**Comment by raypanduro** [comment]
+1

**Pull request closed without merging**
