### PR TITLE
[SPOT-123] Bring licensing into line with ASF policy

### PR DESCRIPTION
**Pull request by srowen**
It's a big change, but a simple one, to try to align the repo's source with ASF policy at https://www.apache.org/legal/src-headers.html

- Add ASF license header to all source
- Restore MIT license to one included JS file
- Remove redundant LICENSE files
- Add basic NOTICE

### CODE REVIEW

**Comment by EverLoSa** [comment]
+1

**Comment by natedogs911** [comment]
the PR is good,
can you add a jira to attach this to? once this is done we can merge.

**Comment by srowen** [comment]
@natedogs911 done as https://issues.apache.org/jira/browse/SPOT-123

**Comment by natedogs911** [comment]
merging

**Comment by srowen** [comment]
Thanks! looks like I can close this.

**Pull request closed without merging**
