### PR TITLE
SPOT-155

### PR DESCRIPTION
**Pull request by bryanmontesv**
Before, "suspicious view" from Flow, Dns and Proxy used to have an Ipython Notebook to scoring threats.
Now Ipython Notebook has been replaced by React & flux, this will help the platform for not depending from Ipython web server and make it friendly with any kind of web service.
This change is only the beginning of several improvements into the UI, this will help us to add more features and not to depend of some technologies to reach our goal.

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by LedaLima** [comment]
The documentation needs to be updated before we merge this change

**Comment by LedaLima** [comment]
+1

**Comment by lujacab** [comment]
+1

**Pull request closed without merging**
