### PR TITLE
SPOT-138 Updating the ONI references with Apache Spot in the README.md file

### PR DESCRIPTION
**Pull request by raypanduro**
Updating the ONI references with Apache Spot in the README.md file and updates in the spot-nfdump link, I also update the approval process to reflect the current process using the +1 to approve the pull requests instead the LGTM.

Closes the bug: https://issues.apache.org/jira/browse/SPOT-138

### CODE REVIEW

**Comment by natedogs911** [comment]
+1

**Comment by LedaLima** [comment]
+1

**Comment by natedogs911** [comment]
Can we get one more review please?

**Comment by EverLoSa** [comment]
+1

**Comment by raypanduro** [comment]
PR merged by Dev team!

**Pull request closed without merging**
