### PR TITLE
[SPOT-277] Updates to Spot Website

### PR DESCRIPTION
**Pull request by schonz**
I've made a couple of updates to the Apache Spot Website on the ASF-Site branch.
1) I've removed all references to Slack
2) I've added links to the Confluence website

There's a new folder called "_Tools". It just contains a python script I used to help me perform the updates faster.

### CODE REVIEW

**Comment by natedogs911** [comment]
+1 with a little hesitance about the confluence wiki as it's not quite bug free yet
But I think we need to fix the slack issue

**Comment by mhicks-cloudera-com** [comment]
+1

**Comment by schonz** [comment]
Fixed a simple bug, there was a duplicate link to the confluence page on one of the menus. Also, added Node_Modules to .gitignore as is customary.

**Comment by TaddWood** [comment]
+1

**Comment by TaddWood** [comment]
@schonz we should probably update the copyright dates as well, but we can move that into a separate PR for clarity sake.

**Comment by pdion891** [comment]
+1

**Pull request merged**
