### PR TITLE
SPOT-180 Support Hive views as source data for ML modules

### PR DESCRIPTION
**Pull request by curtishoward**
This PR is based on [PR#100](https://github.com/apache/incubator-spot/pull/100) (by [anilreddydonthireddy](https://github.com/anilreddydonthireddy)).  Per PR#100 comments I've made the following updates to Anil's branch:

1. Backed out changes to spot-oa ([SPOT-180](https://issues.apache.org/jira/browse/SPOT-180) changes for OA should happen in a separate PR)
2. Provide options to load data from a Parquet file path _**or**_ from a Hive view/table
3. Fixed and added tests to verify new command line argument usage
4. Updated ml_ops.sh to continue using HDFS Parquet file input path for now

These updates should leave spot-ml in a good state (whether merging into SPOT-180_ODM or master), until ODM source data is available from Hive.

### CODE REVIEW

**Comment by natedogs911** [comment]
+1

**Comment by natedogs911** [comment]
Thanks @anilreddydonthireddy  and @curtishoward interested to see what this allows

**Comment by natedogs911** [comment]
@rabarona can you review?

**Comment by TaddWood** [comment]
+1

**Pull request merged**
