### PR TITLE
Added missing ASF license to css and test files

### PR DESCRIPTION
**Pull request by LedaLima**

### CODE REVIEW

**Comment by rabarona** [comment]
How is that some files already had another version of ASF license?

**Comment by LedaLima** [comment]
It was most likely added by the previous developer, but the RAT tool is still detecting the headers as invalid

**Comment by raypanduro** [comment]
+1

**Comment by lujacab** [comment]
+1

**Comment by mpereaji** [comment]
+1

**Comment by BryanMontes** [comment]
+1

**Pull request merged**
