### PR TITLE
Fix broken ingest_summary generation

### PR DESCRIPTION
**Pull request by castleguarders**
Ingest summary generation is broken across monthly or yearly boundaries. The select logic used to generate summary can only work with dates in the same month. The UI allows for arbitrary date selections as it should. The commit fixes the query generation for flow.

### CODE REVIEW

**Comment by castleguarders** [comment]
# Test / Results
test_dateranges = [
    [2015, 9, 16, 2015, 9, 17],
    [2015, 9, 16, 2015, 10, 4],
    [2015, 1, 1, 2015, 1, 30],
    [2015, 9, 16, 2017, 12, 7],
    [2013, 9, 16, 2017, 10, 7],
    [2016, 12, 16, 2017, 10, 7],
    [2017, 8, 1, 2017, 10, 9],
]

Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2015 AND m = 9 AND d >= 16 AND d <= 17)                                             
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2015 AND m = 9 AND d >=16) OR (y = 2015 AND m = 10 AND d <= 4 )                                             
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2015 AND m = 1 AND d >= 1 AND d <= 30)                                             
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2015 AND m = 9 AND d >=16)  OR (y = 2015 AND m > 9)  OR (y = 2016)  OR (y = 2017 AND m < 12)  OR (y = 2017 AND m = 12 and d <= 7)                                            
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2013 AND m = 9 AND d >=16)  OR (y = 2013 AND m > 9)  OR (y = 2014)  OR (y = 2015)  OR (y = 2016)  OR (y = 2017 AND m < 10)  OR (y = 2017 AND m = 10 and d <= 7)                                            
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2016 AND m = 12 AND d >=16)  OR (y = 2017 AND m < 10)  OR (y = 2017 AND m = 10 and d <= 7)                                            
            ORDER BY tdate                                     
            
Executing ingest_summary query                                             
            SELECT                                             
                tdate,total                                    
            FROM spot.flow_ingest_summary                       
            WHERE                                              
                (y = 2017 AND m = 8 AND d >=1) OR (y = 2017 AND m > 8 AND m < 10 ) OR (y = 2017 AND m = 10 AND d <= 9 )                                             
            ORDER BY tdate

**Comment by raypanduro** [comment]
Is there a jira ticket created to track this change? If not can you created please and rename the title of the PR following the naming convention:  **SPOT-XX Title of the PR**

**Comment by natedogs911** [comment]
@castleguarders 
trying to catch these up,
do you have a jira already for this?

also I assume you've submitted an ICLA?
being it's not a significant body of code or an additional feature you may not need one but it's always nice to have it covered.

**Comment by natedogs911** [comment]
I've opened [SPOT-253](https://issues.apache.org/jira/browse/SPOT-253)

Does someone want to own testing this?

Otherwise +1 from me

**Comment by TaddWood** [comment]
+1

**Comment by pdion891** [comment]
+1

**Comment by pdion891** [comment]
+1

**Pull request merged**
