### PR TITLE
Requirements files

### PR DESCRIPTION
**Pull request by natedogs911**
linked to [spot-22](https://issues.apache.org/jira/browse/SPOT-22)

adding pip requirement files, and updated README's to reflect simple install commands

### CODE REVIEW

**Comment by EverLoSa** [comment]
@natedogs911 
What about the INSTAL.md files , should we add something there ? 

https://github.com/apache/incubator-spot/blob/master/spot-oa/oa/INSTALL.md#operational-analytics-installation-and-usage

https://github.com/apache/incubator-spot/blob/master/spot-oa/ui/INSTALL.md#install-spot-ui

**Comment by lujacab** [comment]
+1

**Comment by raypanduro** [comment]
+1

**Comment by EverLoSa** [comment]
+1

**Pull request closed without merging**
