### PR TITLE
[SPOT-291] Update Spot Website Copyright to 2018

### PR DESCRIPTION
**Pull request by schonz**
Updated Copyrights from 2016 to 2018.

Also improved the page-massedit python tool a bit:
- root directory is now dynamic instead of hard-coded
- added substitute feature.

### CODE REVIEW

**Comment by TaddWood** [comment]
+1

**Comment by pdion891** [comment]
+1, would it be possible to update to 2019 while merging the PR ?

**Comment by schonz** [comment]
@pdion891 I'll update it to 2019 by Friday

**Comment by schonz** [comment]
Should be good to go, fixed
- 2019 copyright
- error in user mailing list address

**Pull request merged**
