### PR TITLE
Bluecoat fixes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

I looked at the code for ingesting bluecoat logs and cleaned up a few things along the way.

Cheers
tpltnt

### CODE REVIEW

**Comment by solrac901** [comment]
+1 thanks

**Comment by natedogs911** [comment]
+1 Thanks for the code docs

**Comment by TaddWood** [comment]
+1

**Comment by ktzoulas** [comment]
Hi guys,
As for the file `bluecoat.py`, it should be added the method `partitionBy` to correctly insert data into the Hive table. Otherwise, they are not accessible through Hive. Here is the change:

>  df.write.format('parquet').mode('append')**.partitionBy('y', 'm', 'd', 'h')**.insertInto(hive_table)

**Comment by tpltnt** [comment]
Good idea @ktzoulas. I modified the code to do it.

**Pull request merged**
