### PR TITLE
SPOT-181_ODM Schemas for windows, wg and email data

### PR DESCRIPTION
**Pull request by bjigmp**
Here are new schemas for windows events (field names are based on nxlog fields), WatchGuard events (traffic and dhcp) and Email events (MS Exchange)

Things to discuss:
- Partitioned by year, month and day (using hour and minutes was not effective for our case - too much small files)
- year/month/day have string types. how about use Integer type
- all fields have string type (int type can be used for some fields like size, ports )
- use fieldname conventions (destination vs dst prefix). Maybe switch to ODM

### CODE REVIEW

**Comment by natedogs911** [comment]
We had some issues with partitions being created as Strings but passed to hive as Int's and dropping the leading 0's on days/months < 10.
Curious if this should still be a problem as Hive had some patches regarding this. (I couldn't find them just now but saw it before)

Also do these need to be added to current setup scripts?
I think this could lead to more discussion about pipelines or data sources that someone may choose not to use, should those tables still be generated? 
Perhaps we should move everything into an  *.hql.template and require the .template to be removed for the bash script to pick it up?

**Comment by bjigmp** [comment]
We also use string type for year/month/day. But it's more logical to use integer type.
So that's why I asked.

Regarding adding to setup script. Yes, creation can be optional and configured before installation.
Here is only schemes for physical tables. Also I will going to add several views that normalize data from tables (map fields to some predefined schema, it can be CEF, ODM etc). In our case this is event oriented views (User Login, Administrator Activity and other) 

Also could you please clarify your idea about templates/bash script. Thanks

**Comment by moy8011** [comment]
A couple of questions:
How do you call the SQL files to create the views?
Do you have a sample dataset to test emails,  windows events and WatchGuard events?

**Comment by bjigmp** [comment]
In our solution these views are created by installer. It just runs Hive and Presto binary with this file as parameter and other options (database, etc)
Yes we have (live) data for for MS Exchange, Windows (NX Log) and WatchGuard events.
If you need these data I have to get some confirmations from my side to share it here.

**Comment by natedogs911** [comment]
+1

It would be great to fit this in with the spot-setup/odm folder but this can be done in a new PR.
We'll need to do some testing and playing to fit everything together nicely

**Pull request merged**
