### PR TITLE
Adding missing Apache License

### PR DESCRIPTION
**Pull request by EverLoSa**
Adding Apache License to: 
/spot-ingest/common/__init__.py
/spot-ingest/pipelines/__init__.py
/spot-ingest/pipelines/dns/__init__.py
/spot-ingest/pipelines/flow/__init__.py
/spot-ingest/pipelines/proxy/__init__.py

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by LedaLima** [comment]
+1

**Comment by natedogs911** [comment]
+1

**Comment by natedogs911** [comment]
which jira is this under?

**Comment by lujacab** [comment]
+1

**Pull request closed without merging**
