### PR TITLE
Added missing ASF license to spot-ml files in the RAT report.

### PR DESCRIPTION
**Pull request by rabarona**
Files updated:

  ../incubator-spot/spot-ml/project/plugins.sbt
  ../incubator-spot/spot-ml/src/test/resources/log4j.properties
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/SuspiciousConnectsArgumentParserTest.scala
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/dns/DNSSuspiciousConnectsModelTest.scala
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/netflow/FlowRecord.scala
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/netflow/model/FlowSuspiciousConnectsModelTest.scala
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/utilities/FloatPointPrecisionUtility32Test.scala
  ../incubator-spot/spot-ml/src/test/scala/org/apache/spot/utilities/FloatingPointUtility64.scala

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by vgonzale78** [comment]
+1

**Comment by lujacab** [comment]
+1

**Comment by mpereaji** [comment]
+1

**Comment by rabarona** [comment]
Merged by @LedaLima, thanks.

**Pull request closed without merging**
