### PR TITLE
Removing old references to ONI in OA documentation

### PR DESCRIPTION
**Pull request by LedaLima**
Quick fix - Replaced some left over references to ONI with the new projects name 'Apache Spot'
https://issues.apache.org/jira/browse/SPOT-30

### CODE REVIEW

**Comment by raypanduro** [comment]
+1

**Comment by raypanduro** [comment]
+1

**Comment by EverLoSa** [comment]
+1

**Comment by LedaLima** [comment]
Closing this PR, its a duplicate for #18

**Pull request closed without merging**
