### PR TITLE
SPOT-226. [Ingest] StreamSets pipeline configurations for ODM ingest

### PR DESCRIPTION
**Pull request by jnatkins**
This will add StreamSets pipeline configurations for Qualys APIs, Centrify Identity Platform events, and Windows Events.

### CODE REVIEW

**Comment by raypanduro** [comment]
If this PR is related to ODM, please submit this PR to ODM topic branch https://github.com/apache/incubator-spot/tree/SPOT-181_ODM

**Comment by jnatkins** [comment]
Sorry about that! I've re-targeted this PR against the SPOT-181_ODM branch.

**Comment by jnatkins** [comment]
In an effort to provide some more visibility into the logic here, I'm attaching screenshots of the pipelines as they would be imported into the SDC. They're all parameterized, so that they can be started using filled-in variables relevant to the Spot environment.

screen shot 2017-09-21 at 11 12 17 am
screen shot 2017-09-21 at 11 12 36 am
screen shot 2017-09-21 at 11 12 49 am
screen shot 2017-09-21 at 11 13 05 am
screen shot 2017-09-21 at 11 13 41 am

**Comment by jnatkins** [comment]
Abandoning this PR in favor of a new one that is correctly rebased

**Pull request closed without merging**
