### PR TITLE
Ingest summary enhancements

### PR DESCRIPTION
**Pull request by LedaLima**
- Ingest summary support for all use cases, Netflow, DNS and Proxy   
- OA Module - This process removes duplicated values when executing the same day several times for the same pipeline
- OA - Fixed bug where the header was being replicated in different positions of the file with every execution
- UI - Ingest summary is now a top level section in the main menu
- UI - The ingest summary webpage now displays 3 use cases: Netflow, DNS and Proxy

### CODE REVIEW

**Comment by EverLoSa** [comment]
Linked to [spot-27](https://issues.apache.org/jira/browse/SPOT-27)

**Comment by EverLoSa** [comment]
+1

**Comment by daortizh** [comment]
+1

**Comment by rabarona** [comment]
+1

**Pull request closed without merging**
