### PR TITLE
Spot 181 odm

### PR DESCRIPTION
**Pull request by tzhou2018**
./ml_ops.sh 20181102 flow 5000 0.5
The order of the two parameters needs to be changed.

### CODE REVIEW

**Comment by JonZeolla** [comment]
Awesome contribution.  Can you talk a little bit more to the background/motivation or how someone should approach reviewing it?  I do see that the JIRA also mentions "As a user I want to ingest and use different data sources with Apache Spot using a predefined schema". Thanks

**Comment by schonz** [comment]
Hi @tzhou2018,
Are you attempting to resolve the JIRA Issue Spot-181 with this PR?

**Comment by TaddWood** [comment]
@tzhou2018 it appears that you might've committed your changes against the SPOT-181 branch, but the scope of your changes seem to be a bit smaller:

./ml_ops.sh 20181102 flow 5000 0.5
The order of the two parameters needs to be changed.

Can you confirm, and if so can you create a separate branch off of "master" for these changes as well as a JIRA ticket detailing the changes you're proposing with respect to the ml_ops.sh script?

**Comment by dataminion** [comment]
We are closing this branch because of lack of feedback beyond 6 months

**Pull request closed without merging**
