### PR TITLE
SPOT-33 OA/UI Remove CSVs files as storage layer for Spot results

### PR DESCRIPTION
**Pull request by daortizh**
– New GraphQL API to query data from HDFS parquet files instead of Local File System CSV files
– Modify OA module to save data in HDFS instead of CSVs files.
– Create API to get spot data from HDFS (Impala).
– Modify ML component to read feedback direct from HDFS.

### CODE REVIEW

**Comment by EverLoSa** [comment]
Issue: [SPOT-35](https://issues.apache.org/jira/browse/SPOT-35)

**Comment by dataminion** [comment]
This is a pretty epic pull request, and having reviewed the work I think its really good. 

But from a continuity engineering perspective. I think there is too much work in this ticket for a single PR I am guessing I will be overruled but I think that SPOT 35 should be broken out. for better discussion.

ticket 1
– Modify OA module to save data in HDFS instead of CSVs files.
– Modify ML component to read feedback direct from HDFS.


ticket 2
– Use GraphQL to query data from HDFS parquet files instead of Local File System CSV files
– Create API to get spot data from HDFS (Hive/Impala).

**Comment by EverLoSa** [comment]
Hi @dataminion 

Certainly,  this new functionality must have been a topic branch. You are right,  there are too many commits for a single PR, but the true  is, that if we separate this into different PRs the solution won't  be end to end functional with a single PR.

Maybe this should be changed to a topic branch.  but the effect would be the same.

**Comment by dataminion** [comment]
@EverLoSa so there is nothing wrong with having a PR that doesn't produce end to end functionality. You are confusing the idea of a PR with a feature or release branch. Part of the goal of consistent PR's is to give the community the ability to vet and understand the work. There is so much complexity in these 300+ commits that becomes a challenge. I think that ultimately we should merge this, but it is a good leading indicator that we need to clarify what tickets are producing and how the release cycle (I saw the email flowting in dev about this) will get implemented

**Comment by EverLoSa** [comment]
I think the PR should not merged because it is not the correct path. This PR needs to be closed and review how to approach this merge.  As I mentioned before, this could be treated as topic branch , but lets discuss that in the dev channel.

**Comment by daortizh** [comment]
Closing PR, we need to review this feature because of the number of commits.

**Comment by anilreddydonthireddy** [comment]
may I know if this pull request is merged to release branch or master branch!

**Pull request closed without merging**
