### PR TITLE
[SPOT-181] spot-ingest for ODM with config-driven Spark streaming (Envelope)

### PR DESCRIPTION
**Pull request by curtishoward**

### CODE REVIEW

**Comment by TaddWood** [comment]
@curtishoward I this is really solid work.  The only barrier I see is that Envelope seems to have a hard requirement to use CDH.  Let me know if that's not the case.

## Requirements (From Envelope)

Envelope requires a CDH5.7+ cluster with:
- Cloudera's distribution of Apache Spark 2.2.0 Release 2 or above
- Cloudera's distribution of Apache Kafka 2.1.0 (based on Apache Kafka 0.10) or above, if using that component
- Cloudera's distribution of Apache Kudu 1.3.0 or above, if using that component

**Comment by curtishoward** [comment]
@TaddWood - thanks.  There are plans to eliminate the CDH dependencies, I'll check on the timeline for that and get back to you

**Comment by curtishoward** [comment]
Hi @TaddWood - [Envelope 0.6.0](https://github.com/cloudera-labs/envelope) was released last week, and it now uses upstream Apache dependencies (rather than CDH services)

**Comment by TaddWood** [comment]
+1

**Comment by pdion891** [comment]
+1

**Pull request merged**
