### PR TITLE
Update sbt assembly

### PR DESCRIPTION
**Pull request by Empty-S**

### CODE REVIEW

**Comment by natedogs911** [comment]
+1

**Comment by TaddWood** [comment]
+1

**Comment by schonz** [comment]
Hello @Empty-S 
Thank you for your contributions. In order to complete this Pull Request just a couple of things need to be completed.

1) Please open a Jira Issue [here](https://issues.apache.org/jira/projects/SPOT/issues).
2) Then add that to the title of this PR "[SPOT-###] Update sbt assembly"

Thank you again for your contribution.

**Comment by TaddWood** [comment]
Resolves https://issues.apache.org/jira/browse/SPOT-284

**Pull request merged**
