### PR TITLE
Clarify statements regarding the use of CDH

### PR DESCRIPTION
**Pull request by dataminion**
These changes have been made as a result of discussions on dev@spot.incubator.apache.org in the thread "Inappropriate web site"

### CODE REVIEW

**Comment by JonZeolla** [comment]
Direct [permalink](https://lists.apache.org/thread.html/21d7c8771811ccb305eddc9a26ed05c47a55eb0d87b55c9d415449c9@%3Cdev.spot.apache.org%3E) to the thread.

**Comment by markgrover** [comment]
+1

**Comment by vgonzale78** [comment]
+1

**Comment by EverLoSa** [comment]
+1

**Comment by natedogs911** [comment]
Can we get a Jira attached to this?
I can open one if you need me to @dataminion 
without it the ASF bots aren't happy

**Comment by dataminion** [comment]
This PR resolves SPOT-143

**Comment by natedogs911** [comment]
Thank you,
https://issues.apache.org/jira/browse/SPOT-143
Merging...

**Pull request merged**
