### PR TITLE
Remove hardcoded gti reputation

### PR DESCRIPTION
**Pull request by castleguarders**
Use the reputation services defined by the user in reputation json file instead.

### CODE REVIEW

**Comment by castleguarders** [comment]
Yes. Tested with 
a) Default shipped json, with gti and fb sections. Used as is without any further configuration. i.e. no gti client, or fb threatexchange creds.
b) Added in house rep service along with the above.
c) No services configured in json
d) Only in house rep service 

Can't test with other combos as I don't have fb or gti accounts.

**Comment by natedogs911** [comment]
+1

**Comment by natedogs911** [comment]
just a friendly note,

Per the new rules I'll give this 48 hours as a courtesy  and then merge.

**Comment by raypanduro** [comment]
Is there a jira ticket created to track this change? If not can you created please and rename the title of the PR following the naming convention:  **SPOT-XX Title of the PR**

**Pull request merged**
