### PR TITLE
[SPOT-276] Update odm_setup.sh

### PR DESCRIPTION
**Pull request by annadorottya**
Example for format argument usage corrected.

### CODE REVIEW

**Comment by schonz** [comment]
Hi and Thanks for the PR. 
Could you please open a [Jira ticket here](https://issues.apache.org/jira/projects/SPOT/issues/SPOT-237?filter=allopenissues) and reference it's ID (SPOT-###) in the title.
Thanks!

**Comment by annadorottya** [comment]
Hi,
I already opened a Jira ticket, and now this PR reflects it as well.

**Comment by TaddWood** [comment]
+1

**Comment by mohicksiii** [comment]
+1

**Comment by annadorottya** [comment]
I discovered a very similar problem to the previous one: the ml_ops.sh has two optional arguments: TOL and MAX_RESULTS, in this order, not the other way around (It is documented correctly in ML_OPS.md.)
I didn't open a new pull request or Jira ticket for it, I hope it is all right.

**Pull request merged**
