### PR TITLE
[SPOT-216] hdfs_setup.sh additions to support hive  + some tweaks

### PR DESCRIPTION
**Pull request by natedogs911**
First stage in [#SPOT-216](https://issues.apache.org/jira/browse/SPOT-216)

## file changes:
* split the HQL scripts by database application hive scripts to ./hive/ and impala scripts to ./impala/ etc

## spot.conf
* added DBENGINE to preselect hive cli, impala cli, or beeline with JDBC url
* added JDBC_URL (tested with kerberos)

## hdfs_setup.sh:
* added `set -e` to stop on errors
* using case to parse options
* added --no-sudo to control rather `sudo -u hdfs hdfs ...` is used or `hdfs` in addition to the $HADOOP_USER_NAME field *kept this safe so that you can set the env var prior to running*
* added `-c /some/location/for/spot.conf` as an option to use custom locations. This is intended to make it easier for test&dev
* logic to use `DBENGINE='hive' # hive,impala supported`
* added `-d [hive,impala,beeline]` option to hdfs_setup.sh
* using some functions to keep from having errors from existing folders. this is mainly due to cases where an error occurred and the script was re-run.

## *.hql scripts:
* added `IF NOT EXISTS` to create table commands

### CODE REVIEW

**Comment by jarcec** [comment]
I wonder if we are worried about getting the different HQL scripts out of sync when we start adding columns and other metadata?

**Comment by solrac901** [comment]
+1

**Comment by natedogs911** [comment]
@jarcec I agree it could be a concern.
Is this something that can be addressed down the road?

My thoughts are,

1. Review the scripts and see if there are additional steps to bring them inline, for instance the way the hiveconf variables are being used is probably not correct and i fixed it in the beeline version.

2. would a more programmatic approach to setup (python etc) being unity to the select statements?

**Comment by jarcec** [comment]
Oh, I absolutely think that it's something that we can deal with down the road - don't let my question stop the progress here :)

+1

**Comment by anilreddydonthireddy** [comment]
Hi,
I would like to know if this PR is validated and merged to master branch?
Thanks.

**Comment by natedogs911** [comment]
Hi @anilreddydonthireddy currently all PR's require three +1's from PMC committers,
however I've recently [proposed](https://lists.apache.org/thread.html/ce51f119a2246a48869871ddca5b1eb47d66622673f736845b666a2e@%3Cdev.spot.apache.org%3E) moving to a more traditional approach as this is slowing development.

we did get positive votes from that thread, so i think we need to implement the change.

**Comment by natedogs911** [comment]
I'm closing this one as I've updated some things and included the changes in #134

**Pull request closed without merging**
